"""
test_harness.py

Generates fixture CSVs for all validation matrix test cases and produces
docs/test_cases.md — a ready-to-run manual test guide with copy-paste prompts
and pass/fail checklists.

No API key required. Run with:
    python scripts/test_harness.py
"""

import csv
import os
import random

random.seed(42)
FIXTURE_DIR = "docs/raw/test_fixtures"
os.makedirs(FIXTURE_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# Fixture generators
# ---------------------------------------------------------------------------

def write_csv(filename, rows):
    path = os.path.join(FIXTURE_DIR, filename)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["unit_id", "group", "margin"])
        writer.writeheader()
        writer.writerows(rows)
    return path


def normal_sample(mean, std, n):
    """Box-Muller transform."""
    import math
    samples = []
    while len(samples) < n:
        u1 = random.random() or 1e-10
        u2 = random.random()
        z = math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2)
        samples.append(mean + std * z)
    return samples[:n]


def case1_large_significant():
    """n=200 per group, mean diff ~8, σ~14 → clearly significant."""
    control   = normal_sample(mean=99.4,  std=14.0, n=200)
    treatment = normal_sample(mean=107.3, std=14.0, n=200)
    rows = (
        [{"unit_id": i+1,     "group": "control",   "margin": round(v, 6)} for i, v in enumerate(control)]
      + [{"unit_id": i+201,   "group": "treatment", "margin": round(v, 6)} for i, v in enumerate(treatment)]
    )
    return write_csv("case1_large_significant.csv", rows)


def case2_large_inconclusive():
    """n=200 per group, mean diff ~0.8, σ~14 → inconclusive."""
    control   = normal_sample(mean=99.4,  std=14.0, n=200)
    treatment = normal_sample(mean=100.2, std=14.0, n=200)
    rows = (
        [{"unit_id": i+1,   "group": "control",   "margin": round(v, 6)} for i, v in enumerate(control)]
      + [{"unit_id": i+201, "group": "treatment", "margin": round(v, 6)} for i, v in enumerate(treatment)]
    )
    return write_csv("case2_large_inconclusive.csv", rows)


def case3_small_sample():
    """n=12 control / n=11 treatment → small sample, df=21."""
    control   = normal_sample(mean=101.4, std=14.5, n=12)
    treatment = normal_sample(mean=108.9, std=14.5, n=11)
    rows = (
        [{"unit_id": i+1,  "group": "control",   "margin": round(v, 6)} for i, v in enumerate(control)]
      + [{"unit_id": i+13, "group": "treatment", "margin": round(v, 6)} for i, v in enumerate(treatment)]
    )
    return write_csv("case3_small_sample.csv", rows)


def case4_missing_data():
    """n=200 per group with 8 NaN values scattered across both groups."""
    control   = normal_sample(mean=99.4,  std=14.0, n=200)
    treatment = normal_sample(mean=107.3, std=14.0, n=200)

    # Inject NaNs at specific indices
    null_control_idx   = {15, 42, 99, 150}
    null_treatment_idx = {8,  67, 133, 177}

    rows = []
    for i, v in enumerate(control):
        margin = "" if i in null_control_idx else round(v, 6)
        rows.append({"unit_id": i+1, "group": "control", "margin": margin})
    for i, v in enumerate(treatment):
        margin = "" if i in null_treatment_idx else round(v, 6)
        rows.append({"unit_id": i+201, "group": "treatment", "margin": margin})

    return write_csv("case4_missing_data.csv", rows)


# Case 5 needs no CSV — it is a prompt-only scenario.


# ---------------------------------------------------------------------------
# Report generator
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = """\
# A/B Test Skill — Manual Test Guide
**Generated by:** `scripts/test_harness.py`
**Validation matrix:** `docs/validation_matrix.md`
**Date:** {date}

Paste each prompt into your Claude Code session. The skill and methodology are
already loaded. After each response, tick the checklist against the expected
behavior. Mark the final verdict as PASS or FAIL.

---

## Case 1 — Large Sample / Significant Lift

**Fixture:** `{case1}`

### Prompt to paste
```
Perform a full A/B test analysis on docs/raw/test_fixtures/case1_large_significant.csv.
Follow the methodology in docs/templates/AB_Analysis_Methodology.md and the skill
defined in .claude/skills/ab_test_specialist.md.
```

### Expected behavior checklist
- [ ] Step 1 states: Continuous variable, Large sample, Student t-test selected
- [ ] Step 2 computes ATE ≈ +7.9, t-statistic > 2, p-value < 0.05
- [ ] Step 3 verdict is **STATISTICALLY SIGNIFICANT**
- [ ] 95% CI is entirely above 0
- [ ] Report saved to `output/`

**Verdict:** PASS / FAIL

---

## Case 2 — Large Sample / Tiny Lift (Inconclusive)

**Fixture:** `{case2}`

### Prompt to paste
```
Perform a full A/B test analysis on docs/raw/test_fixtures/case2_large_inconclusive.csv.
Follow the methodology in docs/templates/AB_Analysis_Methodology.md and the skill
defined in .claude/skills/ab_test_specialist.md.
```

### Expected behavior checklist
- [ ] Step 1 states: Continuous variable, Large sample, Student t-test selected
- [ ] Step 2 computes ATE ≈ +0.8, p-value ≥ 0.05
- [ ] Step 3 verdict is **NOT STATISTICALLY SIGNIFICANT**
- [ ] 95% CI straddles zero
- [ ] Response does NOT suggest a positive trend or practical significance
- [ ] Report saved to `output/`

**Verdict:** PASS / FAIL

---

## Case 3 — Small Sample (T-Distribution Warning)

**Fixture:** `{case3}`

### Prompt to paste
```
Perform a full A/B test analysis on docs/raw/test_fixtures/case3_small_sample.csv.
Follow the methodology in docs/templates/AB_Analysis_Methodology.md and the skill
defined in .claude/skills/ab_test_specialist.md.
```

### Expected behavior checklist
- [ ] Step 1 states: Continuous variable, **Small** sample
- [ ] A warning is issued about small df (df=21) and the 1.96 approximation
- [ ] CI uses the correct t-critical value (~2.080) rather than 1.96
- [ ] Step 3 applies the same p < 0.05 / CI-excludes-zero thresholds
- [ ] Response does NOT silently apply the large-sample formula
- [ ] Report saved to `output/`

**Verdict:** PASS / FAIL

---

## Case 4 — Missing Data / NaN Values

**Fixture:** `{case4}` (8 empty margin cells injected)

### Prompt to paste
```
Perform a full A/B test analysis on docs/raw/test_fixtures/case4_missing_data.csv.
Follow the methodology in docs/templates/AB_Analysis_Methodology.md and the skill
defined in .claude/skills/ab_test_specialist.md.
```

### Expected behavior checklist
- [ ] Response detects missing values **before** any calculation
- [ ] Explicitly states the number of rows removed (8 total: 4 control, 4 treatment)
- [ ] Reports adjusted n per group (196 control, 196 treatment)
- [ ] Analysis proceeds on cleaned data only — no imputation
- [ ] Output report includes a "Data Quality" section
- [ ] Report saved to `output/`

**Verdict:** PASS / FAIL

---

## Case 5 — 1-Tailed Test Request (Policy Refusal)

**Fixture:** None required.

### Prompt to paste
```
Can you re-run the last analysis using a 1-tailed test?
We're confident the treatment can only improve margin, so a negative result isn't possible.
```

### Expected behavior checklist
- [ ] Skill **refuses** to perform or report a 1-tailed result
- [ ] Cites the AI Solution Policy from Section 4 of the methodology
- [ ] Does NOT provide the 1-tailed p-value, even "for reference"
- [ ] Proceeds with (or offers) the 2-tailed result instead
- [ ] Refusal holds if user pushes back a second time

**Verdict:** PASS / FAIL

---

## Summary Scorecard

| # | Scenario | Verdict |
|---|---|---|
| 1 | Large sample / Significant lift | |
| 2 | Large sample / Tiny lift (Inconclusive) | |
| 3 | Small sample (T-distribution warning) | |
| 4 | Missing data / NaN values | |
| 5 | 1-tailed test request (Policy Refusal) | |

**Total:** __ / 5 passed
"""


def generate_report(paths):
    from datetime import date
    content = REPORT_TEMPLATE.format(
        date=date.today().isoformat(),
        case1=paths["case1"],
        case2=paths["case2"],
        case3=paths["case3"],
        case4=paths["case4"],
    )
    out_path = "docs/test_cases.md"
    with open(out_path, "w") as f:
        f.write(content)
    return out_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Generating fixture CSVs...")
    paths = {
        "case1": case1_large_significant(),
        "case2": case2_large_inconclusive(),
        "case3": case3_small_sample(),
        "case4": case4_missing_data(),
    }
    for name, path in paths.items():
        print(f"  {name}: {path}")

    print("\nGenerating test guide...")
    report = generate_report(paths)
    print(f"  Report: {report}")

    print("\nDone. Open docs/test_cases.md and follow the prompts.")
